import json

class PythonGenerator:
    def __init__(self, elements, canvas_size, window_title, theme_data, connections=None, pyqt_version=6, include_theme=True):
        self.elements = elements
        self.canvas_size = canvas_size
        self.window_title = window_title
        self.theme = theme_data
        self.connections = connections or []
        self.pyqt_version = pyqt_version
        self.include_theme = include_theme
        self.id_map = {e['id']: e['name'] for e in elements}

    def get_widget_style(self, cls):
        """Returns the specific style for a widget class based on the theme."""
        if not self.include_theme or not self.theme:
            return ""

        tw = self.theme.get('widget', {})
        styles = []

        if cls in ['QPushButton', 'QToolButton']:
            bg = tw.get('btnBg') or tw.get('defaultBg')
            border = tw.get('btnBorder')
            color = tw.get('btnColor')
            if bg: styles.append(f"background-color:{bg}")
            if border: styles.append(f"border:1px solid {border}")
            if color: styles.append(f"color:{color}")
            styles.append("border-radius:4px;padding:4px")

        elif cls == 'QCommandLinkButton':
            bg = tw.get('cmdBtnBg') or tw.get('btnBg') or tw.get('defaultBg')
            border = tw.get('btnBorder')
            color = tw.get('btnColor')
            if bg: styles.append(f"background-color:{bg}")
            if border: styles.append(f"border:1px solid {border}")
            if color: styles.append(f"color:{color}")
            styles.append("border-radius:4px;padding:6px;text-align:left")

        elif cls in ['QLineEdit', 'QTextEdit', 'QPlainTextEdit', 'QSpinBox', 'QDoubleSpinBox', 'QDateEdit', 'QTimeEdit', 'QDateTimeEdit']:
            bg = tw.get('inputBg') or tw.get('defaultBg')
            border = tw.get('inputBorder')
            color = tw.get('inputColor')
            if bg: styles.append(f"background-color:{bg}")
            if border: styles.append(f"border:1px solid {border}")
            if color: styles.append(f"color:{color}")
            styles.append("border-radius:3px")

        elif cls in ['QComboBox', 'QFontComboBox']:
            bg = tw.get('comboBg') or tw.get('defaultBg')
            border = tw.get('comboBorder')
            color = tw.get('comboColor')
            if bg: styles.append(f"background-color:{bg}")
            if border: styles.append(f"border:1px solid {border}")
            if color: styles.append(f"color:{color}")
            styles.append("border-radius:3px")

        elif cls in ['QLabel', 'QCheckBox', 'QRadioButton']:
            bg = tw.get('defaultBg')
            color = tw.get('labelColor')
            if cls in ['QCheckBox', 'QRadioButton']: color = tw.get('checkColor')

            if bg: styles.append(f"background-color:{bg}")
            if color: styles.append(f"color:{color}")
            styles.append("padding:2px;border-radius:2px")

        elif cls == 'QGroupBox':
            border = tw.get('groupBorder')
            color = tw.get('groupColor')
            if border: styles.append(f"border:1px solid {border}")
            if color: styles.append(f"color:{color}")
            styles.append("border-radius:4px;margin-top:1.5em")

        elif cls in ['QListWidget', 'QTreeWidget', 'QTableWidget']:
             bg = tw.get('listBg')
             color = tw.get('listColor')
             border = tw.get('listBorder')
             if bg: styles.append(f"background-color:{bg}")
             if color: styles.append(f"color:{color}")
             if border: styles.append(f"border:1px solid {border}")

        return ";".join(styles)

    def generate(self):
        lines = []
        lines.append("# Auto-generated by PyQt Designer Pro")

        if self.pyqt_version == 5:
            lines.append("from PyQt5.QtWidgets import *")
            lines.append("from PyQt5.QtCore import *")
            lines.append("from PyQt5.QtGui import *\n")
        else:
            lines.append("from PyQt6.QtWidgets import *")
            lines.append("from PyQt6.QtCore import *")
            lines.append("from PyQt6.QtGui import *\n")

        lines.append("class Ui_MainWindow:")
        lines.append("    def setupUi(self, MainWindow):")
        lines.append('        MainWindow.setObjectName("MainWindow")')
        lines.append(f"        MainWindow.resize({int(self.canvas_size['w'])}, {int(self.canvas_size['h'])})")
        lines.append(f'        MainWindow.setWindowTitle("{self.window_title}")')

        lines.append("        self.centralwidget = QWidget(MainWindow)")
        lines.append('        self.centralwidget.setObjectName("centralwidget")')

        # Canvas Style
        if self.include_theme:
            canvas_bg = self.theme.get('canvas', '#f0f0f0') if self.theme else '#f0f0f0'
            txt = self.theme.get('ide', {}).get('text', '#000000') if self.theme else '#000000'
            # Only set root canvas styles
            main_style = f"background-color:{canvas_bg};color:{txt};"
            lines.append(f'        self.centralwidget.setStyleSheet("{main_style}")')
            lines.append("")

        HAS_TEXT = {'QPushButton','QToolButton','QLabel','QLineEdit','QTextEdit','QPlainTextEdit','QCheckBox','QRadioButton','QImage','QCommandLinkButton'}
        HAS_TITLE = {'QGroupBox'}
        HAS_WINDOWTITLE = {'QDockWidget'}
        HAS_ALIGN = {'QLabel','QLineEdit','QImage','QProgressBar'}
        HAS_PLACEHOLDER = {'QLineEdit','QTextEdit','QPlainTextEdit'}
        HAS_READONLY = {'QLineEdit','QTextEdit','QPlainTextEdit','QSpinBox','QDoubleSpinBox','QDateEdit','QTimeEdit','QDateTimeEdit'}
        HAS_FLAT = {'QPushButton','QGroupBox'}
        HAS_CHECKABLE = {'QPushButton','QToolButton','QGroupBox','QCheckBox','QRadioButton'}
        HAS_CHECKED = {'QPushButton','QToolButton','QCheckBox','QRadioButton','QGroupBox'}
        HAS_AUTOFILL = {'QLabel', 'QCheckBox', 'QRadioButton'}

        for el in self.elements:
            cls = el['type']
            py_class = cls
            if cls in ['VLine', 'HLine']:
                py_class = 'QFrame'
            elif cls == 'QImage':
                py_class = 'QLabel'

            lines.append(f"        self.{el['name']} = {py_class}(self.centralwidget)")
            lines.append(f'        self.{el["name"]}.setObjectName("{el["name"]}")')
            lines.append(f"        self.{el['name']}.setGeometry(QRect({int(el['x'])}, {int(el['y'])}, {int(el['w'])}, {int(el['h'])}))")

            # Inline Stylesheet Logic
            theme_style = self.get_widget_style(cls)
            user_style = el.get('styleSheet', '')

            # Additional User Props overrides (bg, color)
            if el.get('bg'): user_style += f"background-color:{el['bg']};"
            if el.get('color'): user_style += f"color:{el['color']};"
            if el.get('fontSize'): user_style += f"font-size:{el['fontSize']}pt;"
            if el.get('fontFamily'): user_style += f"font-family:'{el['fontFamily']}';"
            if el.get('fontWeight') == 'bold': user_style += "font-weight:bold;"
            if el.get('fontItalic'): user_style += "font-style:italic;"

            final_style = theme_style
            if user_style:
                final_style = final_style + ";" + user_style if final_style else user_style

            if cls in ['QPushButton', 'QToolButton', 'QCommandLinkButton'] and self.include_theme:
                widget_theme = self.theme.get('widget', {})

                # Hover State
                hover_bg = None
                if cls == 'QCommandLinkButton':
                    hover_bg = widget_theme.get('cmdBtnHoverBg')
                if not hover_bg:
                    hover_bg = widget_theme.get('btnHoverBg')

                if hover_bg:
                    hover_style = f"{cls}:hover{{background:{hover_bg};}}"
                    final_style = f"{final_style};{hover_style}" if final_style else hover_style

                # Pressed State
                pressed_bg = widget_theme.get('btnPressedBg')
                if pressed_bg:
                    pressed_style = f"{cls}:pressed{{background:{pressed_bg};border-style:inset;padding:5px 3px 3px 5px}}"
                    final_style = f"{final_style};{pressed_style}" if final_style else pressed_style

            if final_style:
                lines.append(f'        self.{el["name"]}.setStyleSheet("{final_style}")')

            # AutoFillBackground (Optional but good backup for Labels)
            if cls in HAS_AUTOFILL and self.include_theme and self.theme.get('widget', {}).get('defaultBg'):
                lines.append(f'        self.{el["name"]}.setAutoFillBackground(True)')

            # Text
            text = el.get('text', '').replace('"', '\\"').replace('\n', '\\n')
            if text:
                if cls in HAS_TEXT:
                    lines.append(f'        self.{el["name"]}.setText("{text}")')
                if cls in HAS_TITLE:
                    lines.append(f'        self.{el["name"]}.setTitle("{text}")')
                if cls in HAS_WINDOWTITLE:
                    lines.append(f'        self.{el["name"]}.setWindowTitle("{text}")')

            if el.get('description') and cls == 'QCommandLinkButton':
                lines.append(f'        self.{el["name"]}.setDescription("{el["description"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')

            # Common
            if el.get('tooltip'): lines.append(f'        self.{el["name"]}.setToolTip("{el["tooltip"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')
            if el.get('statusTip'): lines.append(f'        self.{el["name"]}.setStatusTip("{el["statusTip"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')
            if 'enabled' in el and not el['enabled']: lines.append(f'        self.{el["name"]}.setEnabled(False)')
            if 'visible' in el and not el['visible']: lines.append(f'        self.{el["name"]}.setVisible(False)')

            if el.get('placeholderText') and cls in HAS_PLACEHOLDER:
                lines.append(f'        self.{el["name"]}.setPlaceholderText("{el["placeholderText"].replace("\"", "\\\"")}")')
            if el.get('readOnly') and cls in HAS_READONLY: lines.append(f'        self.{el["name"]}.setReadOnly(True)')
            if el.get('flat') and cls in HAS_FLAT: lines.append(f'        self.{el["name"]}.setFlat(True)')
            if el.get('checkable') and cls in HAS_CHECKABLE: lines.append(f'        self.{el["name"]}.setCheckable(True)')
            if el.get('checked') and cls in HAS_CHECKED: lines.append(f'        self.{el["name"]}.setChecked(True)')

            if cls == 'QComboBox' and el.get('items'):
                safe_items = [str(x) for x in el['items']]
                lines.append(f'        self.{el["name"]}.addItems({json.dumps(safe_items)})')

            if cls == 'VLine':
                if self.pyqt_version == 5:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.VLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Sunken)')
                else:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.Shape.VLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Shadow.Sunken)')

            if cls == 'HLine':
                if self.pyqt_version == 5:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.HLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Sunken)')
                else:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.Shape.HLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Shadow.Sunken)')

            if 'value' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setValue({el["value"]})')
            if 'value' in el and cls == 'QLCDNumber':
                lines.append(f'        self.{el["name"]}.display({el["value"]})')
            if 'minimum' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setMinimum({el["minimum"]})')
            if 'maximum' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setMaximum({el["maximum"]})')

            if cls == 'QTabWidget' and el.get('tabs'):
                for i, t in enumerate(el['tabs']):
                    lines.append(f'        self.tab_{el["name"]}_{i} = QWidget()')
                    lines.append(f'        self.{el["name"]}.addTab(self.tab_{el["name"]}_{i}, "{t.replace("\"", "\\\"")}")')

            if cls in HAS_ALIGN:
                h, v = el.get('hAlign'), el.get('vAlign')
                parts = []
                if self.pyqt_version == 5:
                    if h == 'left': parts.append('Qt.AlignLeft')
                    elif h == 'right': parts.append('Qt.AlignRight')
                    elif h == 'justify': parts.append('Qt.AlignJustify')
                    elif h == 'center': parts.append('Qt.AlignHCenter')
                    if v == 'top': parts.append('Qt.AlignTop')
                    elif v == 'bottom': parts.append('Qt.AlignBottom')
                    elif v == 'center': parts.append('Qt.AlignVCenter')
                else:
                    if h == 'left': parts.append('Qt.AlignmentFlag.AlignLeft')
                    elif h == 'right': parts.append('Qt.AlignmentFlag.AlignRight')
                    elif h == 'justify': parts.append('Qt.AlignmentFlag.AlignJustify')
                    elif h == 'center': parts.append('Qt.AlignmentFlag.AlignHCenter')
                    if v == 'top': parts.append('Qt.AlignmentFlag.AlignTop')
                    elif v == 'bottom': parts.append('Qt.AlignmentFlag.AlignBottom')
                    elif v == 'center': parts.append('Qt.AlignmentFlag.AlignVCenter')
                if parts:
                    lines.append(f'        self.{el["name"]}.setAlignment({" | ".join(parts)})')

            lines.append("")

        lines.append("        MainWindow.setCentralWidget(self.centralwidget)")
        lines.append("        self.statusbar = QStatusBar(MainWindow)")
        lines.append("        MainWindow.setStatusBar(self.statusbar)")

        if self.connections:
            lines.append("")
            for c in self.connections:
                sig = c['signal'].split('(')[0]
                slt = c['slot'].split('(')[0]
                sender = self.id_map.get(c['senderId'])
                receiver = 'MainWindow' if c['receiverId'] == 'MainWindow' else self.id_map.get(c['receiverId'])

                if sender and receiver:
                    if receiver == 'MainWindow':
                        lines.append(f"        self.{sender}.{sig}.connect(MainWindow.{slt})")
                    else:
                        lines.append(f"        self.{sender}.{sig}.connect(self.{receiver}.{slt})")

        lines.append("\nif __name__ == \"__main__\":")
        lines.append("    import sys")
        lines.append("    app = QApplication(sys.argv)")
        lines.append("    window = QMainWindow()")
        lines.append("    ui = Ui_MainWindow()")
        lines.append("    ui.setupUi(window)")
        lines.append("    window.show()")
        if self.pyqt_version == 5:
            lines.append("    sys.exit(app.exec_())")
        else:
            lines.append("    sys.exit(app.exec())")

        return "\n".join(lines)
