import json
from .generator_base import BaseGenerator

class PythonGenerator(BaseGenerator):

    def generate(self):
        lines = []
        lines.append("# Auto-generated by PyQt Designer Pro")

        if self.pyqt_version == 5:
            lines.append("from PyQt5.QtWidgets import *")
            lines.append("from PyQt5.QtCore import *")
            lines.append("from PyQt5.QtGui import *\n")
        else:
            lines.append("from PyQt6.QtWidgets import *")
            lines.append("from PyQt6.QtCore import *")
            lines.append("from PyQt6.QtGui import *\n")

        # AutoScaler Class
        lines.append("class AutoScaler(QGraphicsView):")
        lines.append("    def __init__(self, scene, parent=None):")
        lines.append("        super().__init__(scene, parent)")
        if self.pyqt_version == 5:
            lines.append("        self.setFrameShape(QFrame.NoFrame)")
        else:
            lines.append("        self.setFrameShape(QFrame.Shape.NoFrame)")
        lines.append("        self.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff if hasattr(Qt, 'ScrollBarPolicy') else Qt.ScrollBarAlwaysOff)")
        lines.append("        self.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff if hasattr(Qt, 'ScrollBarPolicy') else Qt.ScrollBarAlwaysOff)")
        lines.append("        self.setStyleSheet('background: transparent;')")

        lines.append("    def resizeEvent(self, event):")
        lines.append("        super().resizeEvent(event)")
        if self.pyqt_version == 5:
            lines.append("        self.fitInView(self.sceneRect(), Qt.KeepAspectRatio)")
        else:
            lines.append("        self.fitInView(self.sceneRect(), Qt.AspectRatioMode.KeepAspectRatio)")
        lines.append("")

        lines.append("class Ui_MainWindow:")
        lines.append("    def setupUi(self, MainWindow):")
        lines.append('        MainWindow.setObjectName("MainWindow")')
        lines.append(f"        MainWindow.resize({int(self.canvas_size['w'])}, {int(self.canvas_size['h'])})")
        lines.append(f'        MainWindow.setWindowTitle("{self.window_title}")')

        # Inject Global Stylesheet
        if self.include_theme:
            global_style = self.generate_stylesheet()
            # Escape newlines for python string
            global_style_py = global_style.replace('\n', '')
            lines.append(f'        MainWindow.setStyleSheet("""{global_style}""")')

        # Setup Scene and Container
        lines.append(f"        self.scene = QGraphicsScene(0, 0, {int(self.canvas_size['w'])}, {int(self.canvas_size['h'])})")
        lines.append("        self.container = QWidget()")
        lines.append(f"        self.container.setGeometry(0, 0, {int(self.canvas_size['w'])}, {int(self.canvas_size['h'])})")
        lines.append('        self.container.setObjectName("container")')

        HAS_TEXT = {'QPushButton','QToolButton','QLabel','QLineEdit','QTextEdit','QPlainTextEdit','QCheckBox','QRadioButton','QImage','QCommandLinkButton'}
        HAS_TITLE = {'QGroupBox'}
        HAS_WINDOWTITLE = {'QDockWidget'}
        HAS_ALIGN = {'QLabel','QLineEdit','QImage','QProgressBar'}
        HAS_PLACEHOLDER = {'QLineEdit','QTextEdit','QPlainTextEdit'}
        HAS_READONLY = {'QLineEdit','QTextEdit','QPlainTextEdit','QSpinBox','QDoubleSpinBox','QDateEdit','QTimeEdit','QDateTimeEdit'}
        HAS_FLAT = {'QPushButton','QGroupBox'}
        HAS_CHECKABLE = {'QPushButton','QToolButton','QGroupBox','QCheckBox','QRadioButton'}
        HAS_CHECKED = {'QPushButton','QToolButton','QCheckBox','QRadioButton','QGroupBox'}
        HAS_AUTOFILL = {'QLabel', 'QCheckBox', 'QRadioButton'}

        for el in self.elements:
            cls = el['type']
            py_class = cls
            if cls in ['VLine', 'HLine']:
                py_class = 'QFrame'
            elif cls == 'QImage':
                py_class = 'QLabel'

            # Parent is self.container instead of self.centralwidget
            lines.append(f"        self.{el['name']} = {py_class}(self.container)")
            lines.append(f'        self.{el["name"]}.setObjectName("{el["name"]}")')
            lines.append(f"        self.{el['name']}.setGeometry(QRect({int(el['x'])}, {int(el['y'])}, {int(el['w'])}, {int(el['h'])}))")

            # Inline Stylesheet Logic (User Overrides Only)
            user_style = self.get_user_style_overrides(el)
            if user_style:
                lines.append(f'        self.{el["name"]}.setStyleSheet("{user_style}")')

            # AutoFillBackground (Optional but good backup for Labels)
            if cls in HAS_AUTOFILL and self.include_theme and self.theme.get('widget', {}).get('defaultBg'):
                lines.append(f'        self.{el["name"]}.setAutoFillBackground(True)')

            # Text
            text = el.get('text', '').replace('"', '\\"').replace('\n', '\\n')
            if text:
                if cls in HAS_TEXT:
                    lines.append(f'        self.{el["name"]}.setText("{text}")')
                if cls in HAS_TITLE:
                    lines.append(f'        self.{el["name"]}.setTitle("{text}")')
                if cls in HAS_WINDOWTITLE:
                    lines.append(f'        self.{el["name"]}.setWindowTitle("{text}")')

            if el.get('description') and cls == 'QCommandLinkButton':
                lines.append(f'        self.{el["name"]}.setDescription("{el["description"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')

            # Common
            if el.get('tooltip'): lines.append(f'        self.{el["name"]}.setToolTip("{el["tooltip"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')
            if el.get('statusTip'): lines.append(f'        self.{el["name"]}.setStatusTip("{el["statusTip"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')
            if 'enabled' in el and not el['enabled']: lines.append(f'        self.{el["name"]}.setEnabled(False)')
            if 'visible' in el and not el['visible']: lines.append(f'        self.{el["name"]}.setVisible(False)')

            if el.get('placeholderText') and cls in HAS_PLACEHOLDER:
                lines.append(f'        self.{el["name"]}.setPlaceholderText("{el["placeholderText"].replace("\"", "\\\"")}")')
            if el.get('readOnly') and cls in HAS_READONLY: lines.append(f'        self.{el["name"]}.setReadOnly(True)')
            if el.get('flat') and cls in HAS_FLAT: lines.append(f'        self.{el["name"]}.setFlat(True)')
            if el.get('checkable') and cls in HAS_CHECKABLE: lines.append(f'        self.{el["name"]}.setCheckable(True)')
            if el.get('checked') and cls in HAS_CHECKED: lines.append(f'        self.{el["name"]}.setChecked(True)')

            if cls == 'QComboBox' and el.get('items'):
                safe_items = [str(x) for x in el['items']]
                lines.append(f'        self.{el["name"]}.addItems({json.dumps(safe_items)})')

            if cls == 'VLine':
                if self.pyqt_version == 5:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.VLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Sunken)')
                else:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.Shape.VLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Shadow.Sunken)')

            if cls == 'HLine':
                if self.pyqt_version == 5:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.HLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Sunken)')
                else:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.Shape.HLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Shadow.Sunken)')

            if 'value' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setValue({el["value"]})')
            if 'value' in el and cls == 'QLCDNumber':
                lines.append(f'        self.{el["name"]}.display({el["value"]})')
            if 'minimum' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setMinimum({el["minimum"]})')
            if 'maximum' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setMaximum({el["maximum"]})')

            if cls == 'QTabWidget' and el.get('tabs'):
                for i, t in enumerate(el['tabs']):
                    lines.append(f'        self.tab_{el["name"]}_{i} = QWidget()')
                    lines.append(f'        self.{el["name"]}.addTab(self.tab_{el["name"]}_{i}, "{t.replace("\"", "\\\"")}")')

            if cls in HAS_ALIGN:
                h, v = el.get('hAlign'), el.get('vAlign')
                parts = []
                if self.pyqt_version == 5:
                    if h == 'left': parts.append('Qt.AlignLeft')
                    elif h == 'right': parts.append('Qt.AlignRight')
                    elif h == 'justify': parts.append('Qt.AlignJustify')
                    elif h == 'center': parts.append('Qt.AlignHCenter')
                    if v == 'top': parts.append('Qt.AlignTop')
                    elif v == 'bottom': parts.append('Qt.AlignBottom')
                    elif v == 'center': parts.append('Qt.AlignVCenter')
                else:
                    if h == 'left': parts.append('Qt.AlignmentFlag.AlignLeft')
                    elif h == 'right': parts.append('Qt.AlignmentFlag.AlignRight')
                    elif h == 'justify': parts.append('Qt.AlignmentFlag.AlignJustify')
                    elif h == 'center': parts.append('Qt.AlignmentFlag.AlignHCenter')
                    if v == 'top': parts.append('Qt.AlignmentFlag.AlignTop')
                    elif v == 'bottom': parts.append('Qt.AlignmentFlag.AlignBottom')
                    elif v == 'center': parts.append('Qt.AlignmentFlag.AlignVCenter')
                if parts:
                    lines.append(f'        self.{el["name"]}.setAlignment({" | ".join(parts)})')

            lines.append("")

        # Add container to scene, set view as central
        lines.append("        self.scene.addWidget(self.container)")
        lines.append("        self.view = AutoScaler(self.scene)")
        lines.append('        self.view.setObjectName("view")')
        lines.append("        MainWindow.setCentralWidget(self.view)")

        lines.append("        self.statusbar = QStatusBar(MainWindow)")
        lines.append("        MainWindow.setStatusBar(self.statusbar)")

        if self.connections:
            lines.append("")
            for c in self.connections:
                sig = c['signal'].split('(')[0]
                slt = c['slot'].split('(')[0]
                sender = self.id_map.get(c['senderId'])
                receiver = 'MainWindow' if c['receiverId'] == 'MainWindow' else self.id_map.get(c['receiverId'])

                if sender and receiver:
                    if receiver == 'MainWindow':
                        lines.append(f"        self.{sender}.{sig}.connect(MainWindow.{slt})")
                    else:
                        lines.append(f"        self.{sender}.{sig}.connect(self.{receiver}.{slt})")

        lines.append("\nif __name__ == \"__main__\":")
        lines.append("    import sys")
        lines.append("    app = QApplication(sys.argv)")
        lines.append("    window = QMainWindow()")
        lines.append("    ui = Ui_MainWindow()")
        lines.append("    ui.setupUi(window)")
        lines.append("    window.show()")
        if self.pyqt_version == 5:
            lines.append("    sys.exit(app.exec_())")
        else:
            lines.append("    sys.exit(app.exec())")

        return "\n".join(lines)
