import json

class PythonGenerator:
    def __init__(self, elements, canvas_size, window_title, theme_data, connections=None, pyqt_version=6, include_theme=True):
        self.elements = elements
        self.canvas_size = canvas_size
        self.window_title = window_title
        self.theme = theme_data
        self.connections = connections or []
        self.pyqt_version = pyqt_version
        self.include_theme = include_theme

    def get_global_style(self):
        if not self.include_theme or not self.theme: return ""
        def_bg = self.theme.get('widget', {}).get('defaultBg', '')
        txt = self.theme.get('ide', {}).get('text', '#000000')
        btn_border = self.theme.get('widget', {}).get('btnBorder', '#555')
        input_bg = self.theme.get('widget', {}).get('inputBg', def_bg)
        input_border = self.theme.get('widget', {}).get('inputBorder', '#555')
        combo_bg = self.theme.get('widget', {}).get('comboBg', def_bg)
        combo_border = self.theme.get('widget', {}).get('comboBorder', '#555')
        group_border = self.theme.get('widget', {}).get('groupBorder', '#555')

        css = f"QWidget{{color:{txt};}}"
        if def_bg:
            css += f"""
            QPushButton, QToolButton, QCommandLinkButton{{background-color:{def_bg};border:1px solid {btn_border};border-radius:4px;padding:4px;}}
            QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QDateEdit, QTimeEdit, QDateTimeEdit{{background-color:{input_bg};border:1px solid {input_border};border-radius:3px;}}
            QComboBox, QFontComboBox{{background-color:{combo_bg};border:1px solid {combo_border};border-radius:3px;}}
            QLabel, QCheckBox, QRadioButton{{background-color:{def_bg};padding:2px;border-radius:2px;}}
            QGroupBox{{border:1px solid {group_border};border-radius:4px;margin-top:1.5em;}}
            QGroupBox::title{{subcontrol-origin:margin;subcontrol-position:top left;padding:0 3px;}}
            """
        return css.replace('\n', ' ').strip()

    def generate(self):
        lines = []
        lines.append("# Auto-generated by PyQt Designer Pro")

        # Imports based on version
        if self.pyqt_version == 5:
            lines.append("from PyQt5.QtWidgets import *")
            lines.append("from PyQt5.QtCore import *")
            lines.append("from PyQt5.QtGui import *\n")
        else:
            lines.append("from PyQt6.QtWidgets import *")
            lines.append("from PyQt6.QtCore import *")
            lines.append("from PyQt6.QtGui import *\n")

        lines.append("class Ui_MainWindow:")
        lines.append("    def setupUi(self, MainWindow):")
        lines.append('        MainWindow.setObjectName("MainWindow")')
        lines.append(f"        MainWindow.resize({int(self.canvas_size['w'])}, {int(self.canvas_size['h'])})")
        lines.append(f'        MainWindow.setWindowTitle("{self.window_title}")')

        lines.append("        self.centralwidget = QWidget(MainWindow)")
        lines.append('        self.centralwidget.setObjectName("centralwidget")')

        # Global Stylesheet
        if self.include_theme:
            canvas_bg = self.theme.get('canvas', '#f0f0f0') if self.theme else '#f0f0f0'
            global_css = self.get_global_style()
            main_style = f"background-color:{canvas_bg};" + global_css
            style_str = main_style.replace('"', '\\"')
            lines.append(f'        self.centralwidget.setStyleSheet("{style_str}")')
            lines.append("")

        # Whitelists
        HAS_TEXT = {'QPushButton','QToolButton','QLabel','QLineEdit','QTextEdit','QPlainTextEdit','QCheckBox','QRadioButton','QImage','QCommandLinkButton','QDockWidget'}
        HAS_TITLE = {'QGroupBox'}
        HAS_WINDOWTITLE = {'QDockWidget'}
        HAS_ALIGN = {'QLabel','QLineEdit','QImage','QProgressBar'}
        HAS_PLACEHOLDER = {'QLineEdit','QTextEdit','QPlainTextEdit'}
        HAS_READONLY = {'QLineEdit','QTextEdit','QPlainTextEdit','QSpinBox','QDoubleSpinBox','QDateEdit','QTimeEdit','QDateTimeEdit'}
        HAS_FLAT = {'QPushButton','QGroupBox'}
        HAS_CHECKABLE = {'QPushButton','QToolButton','QGroupBox','QCheckBox','QRadioButton'}
        HAS_CHECKED = {'QPushButton','QToolButton','QCheckBox','QRadioButton','QGroupBox'}
        HAS_AUTOFILL = {'QLabel', 'QCheckBox', 'QRadioButton'}

        for el in self.elements:
            cls = el['type']
            py_class = 'QFrame' if cls in ['VLine', 'HLine'] else cls

            lines.append(f"        self.{el['name']} = {py_class}(self.centralwidget)")
            lines.append(f'        self.{el["name"]}.setObjectName("{el["name"]}")')
            lines.append(f"        self.{el['name']}.setGeometry(QRect({int(el['x'])}, {int(el['y'])}, {int(el['w'])}, {int(el['h'])}))")

            if cls in HAS_AUTOFILL and self.include_theme and self.theme.get('widget', {}).get('defaultBg'):
                lines.append(f'        self.{el["name"]}.setAutoFillBackground(True)')

            # Text
            text = el.get('text', '').replace('"', '\\"').replace('\n', '\\n')
            if text:
                if cls in HAS_TEXT and cls != 'QComboBox' and cls != 'QDockWidget':
                    lines.append(f'        self.{el["name"]}.setText("{text}")')
                if cls in HAS_TITLE:
                    lines.append(f'        self.{el["name"]}.setTitle("{text}")')
                if cls in HAS_WINDOWTITLE:
                    lines.append(f'        self.{el["name"]}.setWindowTitle("{text}")')

            if el.get('description') and cls == 'QCommandLinkButton':
                lines.append(f'        self.{el["name"]}.setDescription("{el["description"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')

            # Common
            if el.get('tooltip'): lines.append(f'        self.{el["name"]}.setToolTip("{el["tooltip"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')
            if el.get('statusTip'): lines.append(f'        self.{el["name"]}.setStatusTip("{el["statusTip"].replace("\"", "\\\"").replace(chr(10), "\\n")}")')
            if 'enabled' in el and not el['enabled']: lines.append(f'        self.{el["name"]}.setEnabled(False)')
            if 'visible' in el and not el['visible']: lines.append(f'        self.{el["name"]}.setVisible(False)')

            # Props
            if el.get('placeholderText') and cls in HAS_PLACEHOLDER:
                lines.append(f'        self.{el["name"]}.setPlaceholderText("{el["placeholderText"].replace("\"", "\\\"")}")')
            if el.get('readOnly') and cls in HAS_READONLY: lines.append(f'        self.{el["name"]}.setReadOnly(True)')
            if el.get('flat') and cls in HAS_FLAT: lines.append(f'        self.{el["name"]}.setFlat(True)')
            if el.get('checkable') and cls in HAS_CHECKABLE: lines.append(f'        self.{el["name"]}.setCheckable(True)')
            if el.get('checked') and cls in HAS_CHECKED: lines.append(f'        self.{el["name"]}.setChecked(True)')

            # List items
            if cls == 'QComboBox' and el.get('items'):
                safe_items = [str(x) for x in el['items']]
                lines.append(f'        self.{el["name"]}.addItems({json.dumps(safe_items)})')

            # Lines
            if cls == 'VLine':
                if self.pyqt_version == 5:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.VLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Sunken)')
                else:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.Shape.VLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Shadow.Sunken)')

            if cls == 'HLine':
                if self.pyqt_version == 5:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.HLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Sunken)')
                else:
                    lines.append(f'        self.{el["name"]}.setFrameShape(QFrame.Shape.HLine)')
                    lines.append(f'        self.{el["name"]}.setFrameShadow(QFrame.Shadow.Sunken)')

            # Values
            if 'value' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setValue({el["value"]})')
            if 'value' in el and cls == 'QLCDNumber':
                lines.append(f'        self.{el["name"]}.display({el["value"]})')
            if 'minimum' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setMinimum({el["minimum"]})')
            if 'maximum' in el and cls in {'QProgressBar', 'QSlider', 'QSpinBox', 'QDoubleSpinBox'}:
                lines.append(f'        self.{el["name"]}.setMaximum({el["maximum"]})')

            # Tabs
            if cls == 'QTabWidget' and el.get('tabs'):
                for i, t in enumerate(el['tabs']):
                    lines.append(f'        self.tab_{el["name"]}_{i} = QWidget()')
                    lines.append(f'        self.{el["name"]}.addTab(self.tab_{el["name"]}_{i}, "{t.replace("\"", "\\\"")}")')

            # Alignment
            if cls in HAS_ALIGN:
                h, v = el.get('hAlign'), el.get('vAlign')
                parts = []

                if self.pyqt_version == 5:
                    # PyQt5 constants
                    if h == 'left': parts.append('Qt.AlignLeft')
                    elif h == 'right': parts.append('Qt.AlignRight')
                    elif h == 'justify': parts.append('Qt.AlignJustify')
                    elif h == 'center': parts.append('Qt.AlignHCenter')

                    if v == 'top': parts.append('Qt.AlignTop')
                    elif v == 'bottom': parts.append('Qt.AlignBottom')
                    elif v == 'center': parts.append('Qt.AlignVCenter')
                else:
                    # PyQt6 Enums
                    if h == 'left': parts.append('Qt.AlignmentFlag.AlignLeft')
                    elif h == 'right': parts.append('Qt.AlignmentFlag.AlignRight')
                    elif h == 'justify': parts.append('Qt.AlignmentFlag.AlignJustify')
                    elif h == 'center': parts.append('Qt.AlignmentFlag.AlignHCenter')

                    if v == 'top': parts.append('Qt.AlignmentFlag.AlignTop')
                    elif v == 'bottom': parts.append('Qt.AlignmentFlag.AlignBottom')
                    elif v == 'center': parts.append('Qt.AlignmentFlag.AlignVCenter')

                if parts:
                    lines.append(f'        self.{el["name"]}.setAlignment({" | ".join(parts)})')

            # Local Stylesheet (overrides)
            ss = el.get('styleSheet', '')
            if el.get('bg'): ss += f"background-color:{el['bg']};"
            if el.get('color'): ss += f"color:{el['color']};"
            if el.get('fontSize'): ss += f"font-size:{el['fontSize']}pt;"
            if el.get('fontFamily'): ss += f"font-family:'{el['fontFamily']}';"
            if el.get('fontWeight') == 'bold': ss += "font-weight:bold;"
            if el.get('fontItalic'): ss += "font-style:italic;"

            if ss:
                lines.append(f'        self.{el["name"]}.setStyleSheet("{ss}")')

            lines.append("")

        lines.append("        MainWindow.setCentralWidget(self.centralwidget)")
        lines.append("        self.statusbar = QStatusBar(MainWindow)")
        lines.append("        MainWindow.setStatusBar(self.statusbar)")

        # Connections
        if self.connections:
            lines.append("")
            for c in self.connections:
                sig = c['signal'].split('(')[0]
                slt = c['slot'].split('(')[0]
                sender = c['sender']
                receiver = c['receiver']

                if receiver == 'MainWindow':
                    lines.append(f"        self.{sender}.{sig}.connect(MainWindow.{slt})")
                else:
                    lines.append(f"        self.{sender}.{sig}.connect(self.{receiver}.{slt})")

        lines.append("\nif __name__ == \"__main__\":")
        lines.append("    import sys")
        lines.append("    app = QApplication(sys.argv)")
        lines.append("    window = QMainWindow()")
        lines.append("    ui = Ui_MainWindow()")
        lines.append("    ui.setupUi(window)")
        lines.append("    window.show()")
        if self.pyqt_version == 5:
            lines.append("    sys.exit(app.exec_())")
        else:
            lines.append("    sys.exit(app.exec())")

        return "\n".join(lines)
